# Generated by Django 5.2.6 on 2025-10-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce_app', '0002_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
