# Generated by Django 5.2.6 on 2025-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce_app', '0004_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
