# Generated by Django 5.2.6 on 2025-10-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce_app', '0006_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='E_commerce_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_commerce_app.product')),
            ],
        ),
    ]
