# Generated by Django 5.2.6 on 2025-11-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce_app', '0008_shippingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
