# Generated by Django 5.2.6 on 2025-11-17 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce_app', '0009_remove_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='E_commerce_app.order'),
        ),
    ]
